# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=gallery.models.group_path)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.Group')),
            ],
        ),
        migrations.AddField(
            model_name='gallery_item',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Group'),
        ),
    ]
