# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 00:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery_item',
            old_name='group',
            new_name='parent',
        ),
        migrations.AlterOrderWithRespectTo(
            name='gallery_item',
            order_with_respect_to='parent',
        ),
        migrations.AlterOrderWithRespectTo(
            name='group',
            order_with_respect_to='parent',
        ),
    ]
