# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20160108_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery_item',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='gallery_item',
            name='image',
            field=models.ImageField(null=True, upload_to=gallery.models.group_path),
        ),
    ]
