# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-02 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_group_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery_item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
