# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-03 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20160502_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('site_image', models.ImageField(null=True, upload_to='')),
                ('site_info', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
