# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-03 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('gallery', '0007_site_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site_info',
            old_name='site_info',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='site_info',
            name='site_image',
        ),
        migrations.AddField(
            model_name='site_info',
            name='site',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
            preserve_default=False,
        ),
    ]
